const PLANS=[
{id:"upperA",name:"上肢 A",subtitle:"背部 / 体态优先",exercises:[ex("lat_pulldown","高位下拉","背阔肌 / 二头",2,8,12,"reps"),ex("seated_row","坐姿划船","中背 / 背阔肌",2,8,12,"reps"),ex("chest_press","坐姿推胸","胸 / 三头",2,8,12,"reps"),ex("reverse_fly","反向飞鸟","后肩 / 肩胛稳定",2,12,15,"reps"),ex("biceps_curl","二头弯举","二头肌",2,10,15,"reps"),ex("face_pull","Face Pull","后肩 / 上背",2,12,15,"reps")]},
{id:"lower",name:"腿 + 核心",subtitle:"上肢恢复日",exercises:[ex("leg_press","腿举","股四头 / 臀",2,10,12,"reps"),ex("leg_curl","腿弯举","大腿后侧",2,10,15,"reps"),ex("calf_raise","提踵","小腿",2,12,15,"reps"),ex("plank","平板支撑","核心",2,30,60,"seconds"),ex("wall_slide","Wall Slide","肩胛控制",2,10,10,"reps"),ex("chest_stretch","胸肌拉伸","胸前侧",2,30,45,"seconds")]},
{id:"upperB",name:"上肢 B",subtitle:"胸肩背综合",exercises:[ex("chest_press","坐姿推胸","胸 / 三头",2,8,12,"reps"),ex("lat_pulldown","高位下拉","背阔肌 / 二头",2,8,12,"reps"),ex("seated_row","坐姿划船","中背 / 背阔肌",2,8,12,"reps"),ex("shoulder_press","肩推","三角肌 / 三头",2,8,12,"reps"),ex("lateral_raise","侧平举","三角肌中束",2,12,15,"reps"),ex("face_pull","Face Pull / 反向飞鸟","后肩 / 肩胛稳定",2,12,15,"reps"),ex("triceps_pushdown","三头下压","三头肌",2,10,15,"reps")]}
];
function ex(id,name,target,sets,min,max,type){return{id,name,target,sets,min,max,type}}
const STORAGE_KEY="gymTrackerV1";let state=loadState(),currentSession=null;
function defaultState(){return{sessions:[],recovery:{back:0,chest:0,arms:0,legs:0,updatedAt:null},settings:{increment:2.5,theme:"light"}}}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?{...defaultState(),...JSON.parse(raw)}:defaultState()}catch(e){return defaultState()}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}function qs(id){return document.getElementById(id)}
function fmtDateTime(iso){return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(iso))}
function daysBetween(a,b){return Math.floor((new Date(b)-new Date(a))/86400000)}function toast(msg){const el=qs("toast");el.textContent=msg;el.classList.remove("hidden");setTimeout(()=>el.classList.add("hidden"),1600)}
function getPlan(id){return PLANS.find(p=>p.id===id)}function lastSessionForExercise(exId){for(const s of [...state.sessions].reverse()){const e=s.exercises.find(x=>x.id===exId&&x.completed);if(e)return{session:s,exercise:e}}return null}
function getLatestStrength(){return[...state.sessions].reverse().find(s=>s.planId!=="lower")}function weekCount(){const now=new Date(),day=(now.getDay()+6)%7,monday=new Date(now);monday.setHours(0,0,0,0);monday.setDate(now.getDate()-day);return state.sessions.filter(s=>new Date(s.finishedAt||s.startedAt)>=monday).length}
function getSuggestedPlan(){if(!state.sessions.length)return PLANS[0];const last=state.sessions[state.sessions.length-1],idx=PLANS.findIndex(p=>p.id===last.planId);return PLANS[(idx+1)%PLANS.length]}
function maxUpperSoreness(){const r=state.recovery;return Math.max(r.back||0,r.chest||0,r.arms||0)}function recoveryStatus(plan){const score=plan.id==="lower"?(state.recovery.legs||0):maxUpperSoreness();if(score>=5)return{label:"建议恢复",cls:"bad",detail:"目标肌群酸痛 ≥5/10，今天更适合休息或改练其他部位。"};if(score>=3)return{label:"谨慎训练",cls:"warn",detail:"仍有明显酸痛。可减轻重量/组数，若动作受限则继续恢复。"};return{label:"可训练",cls:"good",detail:"酸痛较轻；热身动作流畅、无关节痛时可正常训练。"}}
function renderHome(){const plan=getSuggestedPlan(),status=recoveryStatus(plan);qs("nextWorkoutName").textContent=plan.name;qs("nextWorkoutHint").textContent=plan.subtitle;const badge=qs("recoveryBadge");badge.textContent=status.label;badge.className=`badge ${status.cls}`;qs("recoveryAdvice").textContent=status.detail;const last=getLatestStrength();qs("lastStrength").textContent=last?`${daysBetween(last.finishedAt||last.startedAt,new Date())} 天前`:"暂无";qs("weekStrength").textContent=`${weekCount()} 次`;const r=state.recovery;[["back","backSoreness","backVal"],["chest","chestSoreness","chestVal"],["arms","armsSoreness","armsVal"],["legs","legsSoreness","legsVal"]].forEach(([k,i,v])=>{qs(i).value=r[k]||0;qs(v).textContent=r[k]||0});qs("planCards").innerHTML=PLANS.map(p=>`<div class="plan-card"><div class="plan-top"><div><div class="plan-name">${p.name}</div><div class="plan-sub">${p.subtitle}</div></div><button class="ghost small start-plan" data-plan="${p.id}">开始</button></div><div class="plan-exercises">${p.exercises.map(e=>e.name).join(" · ")}</div></div>`).join("");document.querySelectorAll(".start-plan").forEach(b=>b.onclick=()=>startSession(b.dataset.plan))}
function makeExerciseState(e){const prev=lastSessionForExercise(e.id),prevWeight=prev?.exercise?.weight??0,prevRir=prev?.exercise?.rir??3;return{...e,weight:e.type==="seconds"?0:prevWeight,reps:Array(e.sets).fill(e.min),rir:prevRir,completed:false}}
function startSession(planId){const p=getPlan(planId);currentSession={id:(crypto.randomUUID?crypto.randomUUID():String(Date.now())),planId:p.id,planName:p.name,subtitle:p.subtitle,startedAt:new Date().toISOString(),finishedAt:null,bodyWeight:"",energy:3,recovery:{...state.recovery},exercises:p.exercises.map(makeExerciseState)};qs("sessionTitle").textContent=p.name;qs("bodyWeight").value="";qs("energy").value="3";renderExercises();setView("session")}
function num(x){return Number(x||0).toFixed(Number(x)%1?1:0)}function progressionSuggestion(e,prev){if(!prev)return"第一次记录：先以动作标准、RIR 2–3 为主。";const top=prev.reps?.every(r=>Number(r)>=e.max);if(top&&Number(prev.rir)>=2&&e.type!=="seconds")return"上次已达区间上限且仍有余力：这次可考虑增加最小一档重量。";if(Number(prev.rir)<=1)return"上次接近力竭：这次优先保持或略降重量。";return"建议保持上次重量，先把各组稳定做到区间上限。"}
function renderExercises(){const wrap=qs("exerciseList");wrap.innerHTML=currentSession.exercises.map((e,idx)=>{const prev=lastSessionForExercise(e.id);let prevTxt="上次：暂无记录";if(prev){const pe=prev.exercise;prevTxt=`上次：${pe.weight?pe.weight+" kg · ":""}${pe.reps.join(" / ")} ${e.type==="seconds"?"秒":"次"} · RIR ${pe.rir??"—"}`}const suggestion=progressionSuggestion(e,prev?.exercise);return `<div class="exercise-card ${e.completed?"done":""}" data-ex="${idx}"><div class="exercise-title-row"><div><div class="exercise-name">${e.name}</div><div class="exercise-target">${e.target} · ${e.sets} × ${e.min}–${e.max}${e.type==="seconds"?" 秒":""}</div></div><div class="exercise-status">${e.completed?"已完成":""}</div></div><div class="last-record">${prevTxt}</div>${e.type==="seconds"?"":`<div class="weight-control"><button data-action="weight-minus" data-i="${idx}">−</button><div class="weight-box"><span>${num(e.weight)}</span> kg</div><button data-action="weight-plus" data-i="${idx}">＋</button></div>`}<div class="sets">${e.reps.map((r,sidx)=>`<div class="set-row"><div class="set-label">第 ${sidx+1} 组</div><div class="stepper"><button data-action="rep-minus" data-i="${idx}" data-s="${sidx}">−</button><input data-action="rep-input" data-i="${idx}" data-s="${sidx}" inputmode="numeric" value="${r}"><button data-action="rep-plus" data-i="${idx}" data-s="${sidx}">＋</button></div><div class="muted">${e.type==="seconds"?"秒":"次"}</div></div>`).join("")}</div><div class="rir-row"><span class="muted" style="align-self:center">最后一组 RIR</span>${[0,1,2,3,4,5].map(x=>`<button class="rir-chip ${e.rir===x?"active":""}" data-action="rir" data-i="${idx}" data-rir="${x}">${x===5?"5+":x}</button>`).join("")}</div><div class="suggestion">${suggestion}</div><div class="exercise-actions"><button class="ghost" data-action="skip" data-i="${idx}">${e.completed?"重新打开":"跳过"}</button><button class="primary" data-action="complete" data-i="${idx}">${e.completed?"已完成":"完成动作"}</button></div></div>`}).join("");wireExerciseButtons()}
function wireExerciseButtons(){document.querySelectorAll("[data-action]").forEach(el=>{el.onclick=()=>{const i=Number(el.dataset.i),e=currentSession.exercises[i],a=el.dataset.action;if(a==="weight-minus")e.weight=Math.max(0,Number(e.weight)-Number(state.settings.increment||2.5));if(a==="weight-plus")e.weight=Number(e.weight)+Number(state.settings.increment||2.5);if(a==="rep-minus"){const s=Number(el.dataset.s);e.reps[s]=Math.max(0,Number(e.reps[s])-1)}if(a==="rep-plus"){const s=Number(el.dataset.s);e.reps[s]=Number(e.reps[s])+1}if(a==="rir")e.rir=Number(el.dataset.rir);if(a==="complete")e.completed=true;if(a==="skip")e.completed=!e.completed;renderExercises()}});document.querySelectorAll('[data-action="rep-input"]').forEach(inp=>{inp.onchange=()=>{const i=Number(inp.dataset.i),s=Number(inp.dataset.s);currentSession.exercises[i].reps[s]=Math.max(0,Number(inp.value)||0)}})}
function finishSession(){if(!currentSession)return;currentSession.bodyWeight=qs("bodyWeight").value.trim();currentSession.energy=Number(qs("energy").value);currentSession.finishedAt=new Date().toISOString();state.sessions.push(currentSession);saveState();qs("reportText").value=buildReport(currentSession);qs("modal").classList.remove("hidden");renderHistory();renderHome()}
function buildReport(s){const r=s.recovery||{},mins=Math.max(1,Math.round((new Date(s.finishedAt)-new Date(s.startedAt))/60000)),lines=[`${s.finishedAt.slice(0,10)}｜${s.planName}`,"","训练前状态：",`体重：${s.bodyWeight?s.bodyWeight+" kg":"未记录"}`,`酸痛：背 ${r.back??0}/10，胸 ${r.chest??0}/10，手臂 ${r.arms??0}/10，腿 ${r.legs??0}/10`,`精神状态：${["","很差","偏差","一般","不错","很好"][s.energy]}`,""];s.exercises.forEach(e=>{if(!e.completed)return;lines.push(e.name);if(e.weight)lines.push(`${num(e.weight)} kg`);lines.push(`${e.reps.join(" / ")} ${e.type==="seconds"?"秒":"次"}`);lines.push(`最后一组 RIR ${e.rir}`);lines.push("")});lines.push(`训练时长：${mins} min`);lines.push("");lines.push("请根据这次训练记录评估：哪些动作下次该加重量、哪些保持，训练量和恢复安排是否需要调整。");return lines.join("\n")}
function renderHistory(){const wrap=qs("historyList");if(!state.sessions.length){wrap.innerHTML=`<div class="panel muted">还没有训练记录。完成第一次训练后会出现在这里。</div>`;return}wrap.innerHTML=[...state.sessions].reverse().map(s=>{const done=s.exercises.filter(e=>e.completed),summary=done.map(e=>`${e.name} ${e.weight?num(e.weight)+"kg ":""}${e.reps.join("/")}`).join(" · ");return `<div class="history-card"><div class="plan-top"><div><div class="history-title">${s.planName}</div><div class="history-meta">${fmtDateTime(s.finishedAt||s.startedAt)}</div></div><button class="ghost small history-copy" data-id="${s.id}">复制</button></div><div class="history-summary">${summary||"未记录完成动作"}</div></div>`}).join("");document.querySelectorAll(".history-copy").forEach(b=>b.onclick=async()=>{const s=state.sessions.find(x=>x.id===b.dataset.id);await copyText(buildReport(s));toast("已复制训练报告")})}
async function copyText(text){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text);const ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove()}
function download(name,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
function exportCSV(){const rows=[["date","plan","exercise","weight_kg","set_values","rir","body_weight_kg","energy"]];state.sessions.forEach(s=>s.exercises.filter(e=>e.completed).forEach(e=>rows.push([s.finishedAt||s.startedAt,s.planName,e.name,e.weight||"",e.reps.join("|"),e.rir,s.bodyWeight||"",s.energy])));const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(",")).join("\n");download("gym_training_history.csv","\ufeff"+csv,"text/csv;charset=utf-8")}
function saveRecovery(){state.recovery={back:Number(qs("backSoreness").value),chest:Number(qs("chestSoreness").value),arms:Number(qs("armsSoreness").value),legs:Number(qs("legsSoreness").value),updatedAt:new Date().toISOString()};saveState();renderHome();toast("恢复状态已保存")}
function setView(name){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));qs(`view-${name}`).classList.add("active");document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===name));if(name==="history")renderHistory()}
function applyTheme(){document.documentElement.classList.toggle("dark",state.settings.theme==="dark")}
function bind(){document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>setView(b.dataset.view));qs("startSuggestedBtn").onclick=()=>startSession(getSuggestedPlan().id);qs("backHomeBtn").onclick=()=>setView("home");qs("finishSessionBtn").onclick=finishSession;qs("closeModalBtn").onclick=()=>qs("modal").classList.add("hidden");qs("copyReportBtn").onclick=async()=>{await copyText(qs("reportText").value);toast("已复制，可以直接发给 ChatGPT")};qs("shareReportBtn").onclick=async()=>{const text=qs("reportText").value;if(navigator.share)await navigator.share({title:"训练记录",text});else{await copyText(text);toast("当前浏览器不支持分享，已复制")}};qs("saveRecoveryBtn").onclick=saveRecovery;["back","chest","arms","legs"].forEach(k=>{const input=qs(k+"Soreness"),val=qs(k+"Val");input.oninput=()=>val.textContent=input.value});qs("themeBtn").onclick=()=>{state.settings.theme=state.settings.theme==="dark"?"light":"dark";saveState();applyTheme()};qs("defaultIncrement").value=state.settings.increment||2.5;qs("saveSettingsBtn").onclick=()=>{state.settings.increment=Math.max(.5,Number(qs("defaultIncrement").value)||2.5);saveState();toast("设置已保存")};qs("exportJsonBtn").onclick=()=>download("gym_tracker_backup.json",JSON.stringify(state,null,2),"application/json");qs("exportCsvBtn").onclick=exportCSV;qs("importFile").onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());state={...defaultState(),...data};saveState();applyTheme();renderHome();renderHistory();toast("备份已导入")}catch(err){alert("导入失败：不是有效的备份文件。")}};qs("clearDataBtn").onclick=()=>{if(confirm("确定清空全部训练记录吗？这个操作不可撤销。")){state=defaultState();saveState();applyTheme();renderHome();renderHistory();toast("数据已清空")}}}
applyTheme();bind();renderHome();renderHistory();if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./sw.js").catch(()=>{});
